unique_ids:
  forms:
    Form1: DELC66Q7IVZ6KUA4SCKCZTDKA6IFOLCI
  modules: {}
  server_modules:
    ServerModule1: CWZKVXASXXZTE4SQBWHTXR5FX7FBG7KE
  assets:
    standard-page.html: 7RMQSGOQO4LBLJGGZ6FY5YL6W6ZZB26D
    theme.css: FHCBSFYKERNYLSSYM6BISUTW35QOCEMZ
  scripts: {}
